### ISSUE TITLE
Side Menu on mobile not accessible

### ISSUE THREAD

**Issue by mathis1337** [wrappixel/ample-admin-lite#1]
When you view this version on mobile the side menu does collapse, but there is no way to access any of the other items in there. It just shows Dashboard always. It would be nice if it would include all the items in the side nav through like a hamburger menu or something. 

I understand that this is free, but I would consider the ability to navigate a core function for free or paid. If thats not the case all good and you can close this out.

**Comment by MG341531** [comment]
why are you banning people and wallets on RBX ???
